package io.jpress.module.ad.model;

import io.jboot.db.annotation.Table;
import io.jpress.module.ad.model.base.BaseAd;

/**
 * Generated by JPress.
 */
@Table(tableName = "ad", primaryKey = "id")
public class Ad extends BaseAd<Ad> {

    private static final long serialVersionUID = 1L;

	
}

